// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Yesterday$Sharedlib = require("sharedlib/shared/yesterday.bs.js");

console.log("Hello, Melange");

console.log(Yesterday$Sharedlib.yesterday(undefined));

/*  Not a pure module */
